### ISSUE TITLE
Why is this doing a POST where it should do a GET?

### ISSUE THREAD

**Issue by eeeeek** [rstaib/jquery-bootgrid#102]
Why is this doing a POST when the default action for reading data (from a RESTful API) is GET? And why can I not change the method used? 

When, in a real world scenario, is getting data ever a POST? POST is to create a record ... not fetch one, this breaks compatibility with ALL RESTful APIs on the entire internetz. I am not sarcastic, I am really not getting why ... it's so obvious: You are GETting data from a resource when you populate a grid .. not POSTing data to a resource.
 
Please, please accept the pull request by @awelles (60) that's been pending since 5 december 2014.. it solves this issue.

**Comment by rstaib** [comment]
Three points why I considered to use POST instead of GET for the first version of Bootgrid.

POST requests …
1)	will be never cached
2)	are more secure than GET requests (considering you’re using sensitive data by manipulating the request object for your needs via the `requestHandler`)
3)	are not restricted in data length unlike the GET request where the maximum length depends on the server and/or browser and even though long URLs are not a good idea

Nevertheless, the http GET method is already planned and as soon as I have enough time to verify 
the pull request of @awelles and of course accept it I will merge it to HEAD branch.

Thanks you for your request and I hope I could clarify why I started with POST over GET.
