### ISSUE TITLE
select row without showing a checkbox on row

### ISSUE THREAD

**Issue by pashute** [rstaib/jquery-bootgrid#224]
I want to select the row (rowSelect:true) but without a checkbox at the beginning of the row, so that the on(selected...) event will fire.

**Comment by vzbruno** [comment]
Did you found a way? I'm looking for a way to change the checkbox content. I already seen it on a website where instead of a common input checkbox, it's a stylized checkbox with a totally different code. I couldn't find on the documentation how to do it though.

Edit: got it working using templates, I believe you can have the desired effect using templates too, but removing the checkboxes at all.

```
templates: {
  select: "",
},
```

**Comment by pashute** [comment]
Yes you got it correctly. You have to add 'rowSelect: true' of course, otherwise there's no way to select. 

Here's a jsfiddle demonstrating it: https://fiddle.jshell.net/pashute/e6foaxzm/
