### ISSUE TITLE
Displaying HTML in a table cell?

### ISSUE THREAD

**Issue by avlcodemonkey** [rstaib/jquery-bootgrid#34]
I have a situation where I need to display HTML links in a table cell.  I've experimented with using a formatter like your commands example.  The problem is that I need to check user permissions as I build the links, so I need to build the HTML on the backend instead of in the js.  Any suggestions?

**Comment by Nerian** [comment]
And how would we actually render html data?

**Comment by cpittman063** [comment]
Nerian, I ended up building my HTML using a formatter similar to how Rafael suggested.  But I check permissions when setting up bootgrid initially instead of in the response object.  In my table head, I've got an extra column for my buttons like:

<th data-column-id="userActions" data-formatter="userActions" data-sortable="false">Actions</th>

Then in the bootgrid declaration:

formatters: {
	'userActions': function (column, row) {
		var root = '/User/';
		var res = "";
		@if (CurrentUser.HasAccess("User", "Edit")) {
			@Html.Raw("res += '<a href=\"' + root + 'Edit/' + row.id + '\" class=\"btn btn-sm btn-warning\">" + @Html.Raw(Users.LinkEdit) + "</a>';\n")
		}
		@if (CurrentUser.HasAccess("User", "Delete")) {
			@Html.Raw("res += '<a href=\"' + root + 'Delete/' + row.id + '\" class=\"btn btn-sm btn-danger\">" + @Html.Raw(Users.LinkDelete) + "</a>';\n")
		}
		return res;
	}
}

That code just checks the user permissions when the page is initially built.  Does that make sense?

**Comment by Nerian** [comment]
Looks good. I took the same approach and used a formatter. 

I think it would be convenient to package have a HTML formatter.

**Comment by jobnomade** [comment]
I second this. Would be great to have bootgrid use the raw HTML from the backend.
